import { DataType } from '../utils/types/types'

const initialState: DataType[] = [
  {
    ou: '7',
    record: '0-0',
    winPercentage: '0%',
    favRecord: '0-0 / 0%',
    overFavs: '0-0 / 0%',
    dogRecord: '0-0 / 0%',
    notes: '0-0 / 0%',
  },
  {
    ou: '7.5',
    record: '0-0',
    winPercentage: '0%',
    favRecord: '0-0 / 0%',
    overFavs: '0-0 / 0%',
    dogRecord: '0-0 / 0%',
    notes: '0-0 / 0%',
  },
  {
    ou: '8',
    record: '0-0',
    winPercentage: '0%',
    favRecord: '0-0 / 0%',
    overFavs: '0-0 / 0%',
    dogRecord: '0-0 / 0%',
    notes: '0-0 / 0%',
  },
  {
    ou: '8.5',
    record: '0-0',
    winPercentage: '0%',
    favRecord: '0-0 / 0%',
    overFavs: '0-0 / 0%',
    dogRecord: '0-0 / 0%',
    notes: '0-0 / 0%',
  },
  {
    ou: '9',
    record: '0-0',
    winPercentage: '0%',
    favRecord: '0-0 / 0%',
    overFavs: '0-0 / 0%',
    dogRecord: '0-0 / 0%',
    notes: '0-0 / 0%',
  },
  {
    ou: '9.5',
    record: '0-0',
    winPercentage: '0%',
    favRecord: '0-0 / 0%',
    overFavs: '0-0 / 0%',
    dogRecord: '0-0 / 0%',
    notes: '0-0 / 0%',
  },
  {
    ou: '10',
    record: '0-0',
    winPercentage: '0%',
    favRecord: '0-0 / 0%',
    overFavs: '0-0 / 0%',
    dogRecord: '0-0 / 0%',
    notes: '0-0 / 0%',
  },
  {
    ou: '10.5',
    record: '0-0',
    winPercentage: '0%',
    favRecord: '0-0 / 0%',
    overFavs: '0-0 / 0%',
    dogRecord: '0-0 / 0%',
    notes: '0-0 / 0%',
  },
  {
    ou: '11',
    record: '0-0',
    winPercentage: '0%',
    favRecord: '0-0 / 0%',
    overFavs: '0-0 / 0%',
    dogRecord: '0-0 / 0%',
    notes: '0-0 / 0%',
  },
  {
    ou: '11.5-12.5',
    record: '0-0',
    winPercentage: '0%',
    favRecord: '0-0 / 0%',
    overFavs: '0-0 / 0%',
    dogRecord: '0-0 / 0%',
    notes: '0-0 / 0%',
  },
]

export { initialState }
