version: 2.1

jobs:
test:
    docker:
      - image: node:16-alpine
    working_directory: ~/app
    steps:
      - checkout
      - run: 
          command: |
            npm install
            npm run test
  build:
    docker:
      - image: node:16-alpine
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths: 
            - ./node_modules
      - run:
          name: Application Build 
          command: npm run build
       


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample:
    jobs:
      - test
      - build:
          requires:
            - test

