import { DataType } from '../utils/types/types'

const initialState: DataType[] = [
    {
        ou: '7',
        g1FavTwoPointFive: '0-0 / 0%',
        g1FavOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        g1DogTwoPointFive: '0-0 / 0%',
        g1DogOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        favTwoPointFive: '0-0 / 0%',
        favOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        dogTwoPointFive: '0-0 / 0% on o2.5',
        dogOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        homeMLTwoPointFive: '0-0 / 0% on o2.5',
        homeMLThreePointFive: '0-0 / 0% on o3.5',
    },
    {
        ou: '7.5',
        g1FavTwoPointFive: '0-0 / 0%',
        g1FavOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        g1DogTwoPointFive: '0-0 / 0%',
        g1DogOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        favTwoPointFive: '0-0 / 0%',
        favOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        dogTwoPointFive: '0-0 / 0% on o2.5',
        dogOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        homeMLTwoPointFive: '0-0 / 0% on o2.5',
        homeMLThreePointFive: '0-0 / 0% on o3.5',
    },
    {
        ou: '8',
        g1FavTwoPointFive: '0-0 / 0%',
        g1FavOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        g1DogTwoPointFive: '0-0 / 0%',
        g1DogOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        favTwoPointFive: '0-0 / 0%',
        favOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        dogTwoPointFive: '0-0 / 0% on o2.5',
        dogOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        homeMLTwoPointFive: '0-0 / 0% on o2.5',
        homeMLThreePointFive: '0-0 / 0% on o3.5',
    },
    {
        ou: '8.5',
        g1FavTwoPointFive: '0-0 / 0%',
        g1FavOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        g1DogTwoPointFive: '0-0 / 0%',
        g1DogOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        favTwoPointFive: '0-0 / 0%',
        favOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        dogTwoPointFive: '0-0 / 0% on o2.5',
        dogOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        homeMLTwoPointFive: '0-0 / 0% on o2.5',
        homeMLThreePointFive: '0-0 / 0% on o3.5',
    },
    {
        ou: '9',
        g1FavTwoPointFive: '0-0 / 0%',
        g1FavOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        g1DogTwoPointFive: '0-0 / 0%',
        g1DogOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        favTwoPointFive: '0-0 / 0%',
        favOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        dogTwoPointFive: '0-0 / 0% on o2.5',
        dogOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        homeMLTwoPointFive: '0-0 / 0% on o2.5',
        homeMLThreePointFive: '0-0 / 0% on o3.5',
    },
    {
        ou: '9.5',
        g1FavTwoPointFive: '0-0 / 0%',
        g1FavOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        g1DogTwoPointFive: '0-0 / 0%',
        g1DogOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        favTwoPointFive: '0-0 / 0%',
        favOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        dogTwoPointFive: '0-0 / 0% on o2.5',
        dogOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        homeMLTwoPointFive: '0-0 / 0% on o2.5',
        homeMLThreePointFive: '0-0 / 0% on o3.5',
    },
    {
        ou: '10',
        g1FavTwoPointFive: '0-0 / 0%',
        g1FavOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        g1DogTwoPointFive: '0-0 / 0%',
        g1DogOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        favTwoPointFive: '0-0 / 0%',
        favOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        dogTwoPointFive: '0-0 / 0% on o2.5',
        dogOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        homeMLTwoPointFive: '0-0 / 0% on o2.5',
        homeMLThreePointFive: '0-0 / 0% on o3.5',
    },
    {
        ou: '10.5',
        g1FavTwoPointFive: '0-0 / 0%',
        g1FavOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        g1DogTwoPointFive: '0-0 / 0%',
        g1DogOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        favTwoPointFive: '0-0 / 0%',
        favOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        dogTwoPointFive: '0-0 / 0% on o2.5',
        dogOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        homeMLTwoPointFive: '0-0 / 0% on o2.5',
        homeMLThreePointFive: '0-0 / 0% on o3.5',
    },
    {
        ou: '11',
        g1FavTwoPointFive: '0-0 / 0%',
        g1FavOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        g1DogTwoPointFive: '0-0 / 0%',
        g1DogOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        favTwoPointFive: '0-0 / 0%',
        favOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        dogTwoPointFive: '0-0 / 0% on o2.5',
        dogOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        homeMLTwoPointFive: '0-0 / 0% on o2.5',
        homeMLThreePointFive: '0-0 / 0% on o3.5',
    },
    {
        ou: '11.5-12.5',
        g1FavTwoPointFive: '0-0 / 0%',
        g1FavOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        g1DogTwoPointFive: '0-0 / 0%',
        g1DogOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        favTwoPointFive: '0-0 / 0%',
        favOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        dogTwoPointFive: '0-0 / 0% on o2.5',
        dogOnePointFiveThreePointFive: '0-0 / 0% on o1.5',
        homeMLTwoPointFive: '0-0 / 0% on o2.5',
        homeMLThreePointFive: '0-0 / 0% on o3.5',
    },
]

export { initialState }
