enum BASEBALL_TABLE_NAMES {
    baseballHomeNonDivision = 'BASEBALL HOME NON DIVISION',
    baseballHomeDivision = 'BASEBALL HOME DIVISION',
    baseballHomeNonDivision2022 = 'BASEBALL HOME NON DIVISION 2022',
    baseballHomeDivision2022 = 'BASEBALL HOME DIVISION 2022',
}

enum SPORT_NAME {
    BASEBALL = 'BASEBALL',
    FOOTBALL = 'FOOTBALL',
}

export { BASEBALL_TABLE_NAMES, SPORT_NAME }
